### ISSUE TITLE
Souscrire à un 1Password pour le compte de l'asso

### ISSUE THREAD

**Issue by CadiChris** [okiwi/okiwi-assemblees-generales#1]
Actuellement le partage des MDP est très amateur et donc peu sécurisé.
Et chaque mise à jour de MDP peut échapper à un.e ou plusieurs membres du bureau.

Pourquoi ne pas utiliser qq euros de trésorerie pour un 1password.

**Comment by guillaumevincent** [comment]
On avait un fichier keepass à l'époque.
C'est une bonne pratique d'avoir une gestionnaire de mot de passe!

Bitwarden ou 1Password
Le premier est open source

**Comment by CadiChris** [comment]
La question est ajoutée dans le PV 2022. Je ferme cette issue. 

À l'usage ce sera plus simple d'utiliser le fichier `md` du PV.
